### ISSUE TITLE
Get OpenSlide working on computablebrain

### ISSUE THREAD

**Issue by dgutman** [dgutman/ADRCPathViewer#10]
This.. should.. be. .. easy

Use ansible script Brian has already created to do this on an ubuntu machine, and ... run it

1)  More importantly, document on THIS wiki how you did it 

2)  Upload/commit the ansible script snippet you used to this repository in a ansible/setup directory

**Comment by mohammedkhalilia** [comment]
Done. Documentation coming soon!
