### ISSUE TITLE
Set up ComputableBrain

### ISSUE THREAD

**Issue by dgutman** [dgutman/ADRCPathViewer#5]
We need to be able to get the following domains routed 

/  --> index.html ("WElcome to the computable brain!")

mouse.computablebrain.emory.edu   -->  FOR NOW, a second index.html  "Welcome to mouse.computablebrain.emory.edu "

adrc.computablebrain.emory.edu  -->  Flask/Gunicorn Application running the web_service directory

**Comment by mohammedkhalilia** [comment]
http://computablebrain.emory.edu/ is live
I modified index.html in /usr/share/nginx/html
